github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
tasks:
  - name: dev-mode
    init: |
      pip3 install -e ".[docs,test]"
      jlpm install
      jlpm run build
      gp sync-done setup
    # Set no token and allow any origin, so that you can open it in a new tab
    # Disable iframe security so can load in the editor as well
    command: |
      jupyter lab --dev-mode --watch --LabApp.token='' --LabApp.allow_origin=* --LabApp.tornado_settings='{"headers": {"Content-Security-Policy": "frame-ancestors *"}}'
  - name: documentation
    init: |
      gp sync-await setup
      cd docs
      make html
    command: |
      cd build/html
      python -m http.server 8000
ports:
  - port: 8888
  - port: 8000

vscode:
  extensions:
    - esbenp.prettier-vscode
