name: example-environment
channels:
  - conda-forge
dependencies:
  - jupyterlab-link-share=0.2
  - jupyter-server-proxy
  - matplotlib-base
  - nodejs=14
  - numpy
  - pip
  - python=3.8
  - vega_datasets
  - xeus-python
