name: Check internationalization changes

on:
  pull_request:

jobs:
  check_i18n:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-i18n-${{ hashFiles('setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip-i18n-
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install jupyterlab-translate~=1.0

      - name: Compute hash
        id: currentHash
        run: |
          set -eux
          HASH=$(python scripts/i18n_check.py | tail -n1)
          echo "::set-output name=i18n::${HASH}"

      - name: Checkout target
        run: |
          echo Checking ${GITHUB_BASE_REF}...
          # Ref https://github.com/actions/checkout/issues/93
          git fetch --depth=1 origin +refs/heads/${GITHUB_BASE_REF}:refs/remotes/origin/${GITHUB_BASE_REF}
          git checkout ${GITHUB_BASE_REF}

      - name: Check hash
        env:
          CURRENT: ${{ steps.currentHash.outputs.i18n }}
        run: |
          set -eux
          EXPECTED=$(python scripts/i18n_check.py | tail -n1)
          if [[ "${CURRENT}" != "${EXPECTED}" ]]; then
            echo "Translatable strings have changed, this is only allowed on major or minor version bumps."
            # Set job status as failed if
            # - branch is not "master"
            # - and current version is not a pre release of a zeroed patch version
            if [[ "${GITHUB_BASE_REF}" != "master" && ! ( $(python setup.py --version) =~ ^[0-9]+\.[0-9]+\.0(\.dev|a|b|rc)[0-9]+$ ) ]]; then
              exit 1
            fi
          fi
